name: Autograding Tests
'on': {}
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_notebook.py
      id: test_notebook-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 1
        setup-command: |
          pip install numpy matplotlib scipy pytest nbconvert chardet
          nbformat nbclient jupyter ipykernel
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_NOTEBOOK-PY_RESULTS: "${{steps.test_notebook-py.outputs.result}}"
      with:
        runners: test_notebook-py
